# Generated by Django 4.2.6 on 2023-10-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="date_of_birth", field=models.DateField(null=True),
        ),
    ]
