# Generated by Django 4.2.6 on 2023-10-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
