# Generated by Django 4.2.6 on 2023-10-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_order_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount_to_pay",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
