# Generated by Django 4.2.6 on 2023-10-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_order_amount_to_pay"),
    ]

    operations = [
        migrations.AddField(
            model_name="order", name="lid", field=models.UUIDField(null=True),
        ),
    ]
