# Generated by Django 4.2.6 on 2023-12-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_alter_order_lid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="room_type",
            field=models.CharField(max_length=125, null=True),
        ),
    ]
